version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/playground-web
    # overwrite: yes
permissions:
  - object: /home/ubuntu/playground-web
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 60
      runas: root # 작성해주지 않으면 간혹 permission error가 날수도 있음
